// Code generated by ent, DO NOT EDIT.

package ent

import (
	"authflow/ent/oauthclient"
	"authflow/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	oauthclientFields := schema.OAuthClient{}.Fields()
	_ = oauthclientFields
	// oauthclientDescName is the schema descriptor for name field.
	oauthclientDescName := oauthclientFields[1].Descriptor()
	// oauthclient.NameValidator is a validator for the "name" field. It is called by the builders before save.
	oauthclient.NameValidator = oauthclientDescName.Validators[0].(func(string) error)
	// oauthclientDescRedirectURI is the schema descriptor for redirect_uri field.
	oauthclientDescRedirectURI := oauthclientFields[3].Descriptor()
	// oauthclient.RedirectURIValidator is a validator for the "redirect_uri" field. It is called by the builders before save.
	oauthclient.RedirectURIValidator = oauthclientDescRedirectURI.Validators[0].(func(string) error)
	// oauthclientDescCreatedAt is the schema descriptor for created_at field.
	oauthclientDescCreatedAt := oauthclientFields[4].Descriptor()
	// oauthclient.DefaultCreatedAt holds the default value on creation for the created_at field.
	oauthclient.DefaultCreatedAt = oauthclientDescCreatedAt.Default.(func() time.Time)
}
