// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// OAuthClient is the predicate function for oauthclient builders.
type OAuthClient func(*sql.Selector)
